apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiny-etl1-deployment
spec:
  selector:
    matchLabels:
      app: tiny-etl1
  replicas: 1
  template:
    metadata:
      labels:
        app: tiny-etl1
    spec:
      nodeName: k8s-node1 #指定节点名称
      containers:
        - name: tiny-etl
          image: 192.168.102.21:5000/tiny_etl:1.3
          imagePullPolicy: Never
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: tiny-etl1-service
spec:
  type: NodePort
  selector:
    app: tiny-etl1
  ports:
    - port: 8000
      nodePort: 30081
    
